// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using KamuTechApi.Data;
using KamuTechApi.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace KamuTechApi.Data.Configurations
{
    public partial class ComponentTypesConfiguration : IEntityTypeConfiguration<ComponentTypes>
    {
        public void Configure(EntityTypeBuilder<ComponentTypes> entity)
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ComponentTypes> entity);
    }
}
