// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using KamuTechApi.Data;
using KamuTechApi.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace KamuTechApi.Data.Configurations
{
    public partial class PhotoListConfiguration : IEntityTypeConfiguration<PhotoList>
    {
        public void Configure(EntityTypeBuilder<PhotoList> entity)
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.ComponentId).HasColumnName("componentId");

            entity.Property(e => e.ComponentTypeId).HasColumnName("componentTypeId");

            entity.HasOne(d => d.ComponentType)
                .WithMany(p => p.PhotoList)
                .HasForeignKey(d => d.ComponentTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PhotoList_fk1");

            entity.HasOne(d => d.IdNavigation)
                .WithOne(p => p.PhotoList)
                .HasForeignKey<PhotoList>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PhotoList_fk0");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PhotoList> entity);
    }
}
