// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using KamuTechApi.Data;
using KamuTechApi.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace KamuTechApi.Data.Configurations
{
    public partial class SlidersConfiguration : IEntityTypeConfiguration<Sliders>
    {
        public void Configure(EntityTypeBuilder<Sliders> entity)
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name");

            entity.Property(e => e.PhotoId).HasColumnName("photoId");

            entity.HasOne(d => d.Photo)
                .WithMany(p => p.Sliders)
                .HasForeignKey(d => d.PhotoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Sliders_fk0");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Sliders> entity);
    }
}
