// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using KamuTechApi.Data.Configurations;
using KamuTechApi.Models;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace KamuTechApi.Data
{
    public partial class KamutechdbContext : DbContext
    {
        public KamutechdbContext(DbContextOptions<KamutechdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<ComponentTypes> ComponentTypes { get; set; }
        public virtual DbSet<PhotoList> PhotoList { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Sliders> Sliders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(localDb)\\MsSqllocaldb;Initial Catalog=KamuTechDbUdated;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.ArticlesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CardsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CommentsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ComponentTypesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PhotoListConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PhotosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SlidersConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
