// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace KamuTechApi.Models
{
    public partial class Comments
    {
        public int Id { get; set; }
        public int ComponetId { get; set; }
        public string CommentPost { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Position { get; set; }
        public string Organisation { get; set; }
    }
}