// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace KamuTechApi.Models
{
    public partial class ComponentTypes
    {
        public ComponentTypes()
        {
            PhotoList = new HashSet<PhotoList>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<PhotoList> PhotoList { get; set; }
    }
}