// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace KamuTechApi.Models
{
    public partial class Photos
    {
        public int Id { get; set; }
        public int? ComponentId { get; set; }
        public DateTime DateAdded { get; set; }
        public string Description { get; set; }
        public byte[] IsMain { get; set; }
        public string Url { get; set; }
        public string PublicId { get; set; }
    }
}