// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace KamuTechApi.Models
{
    public partial class PhotoList
    {
        public PhotoList()
        {
            Articles = new HashSet<Articles>();
            Cards = new HashSet<Cards>();
            Comments = new HashSet<Comments>();
            Sliders = new HashSet<Sliders>();
        }

        public int Id { get; set; }
        public int ComponentId { get; set; }
        public int ComponentTypeId { get; set; }

        public virtual ComponentTypes ComponentType { get; set; }
        public virtual Photos IdNavigation { get; set; }
        public virtual ICollection<Articles> Articles { get; set; }
        public virtual ICollection<Cards> Cards { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<Sliders> Sliders { get; set; }
    }
}